[project]
name = "tado-exporter"
description = "A simple exporter for Tado data"
authors = [
    { name = "Dennis", email = "dennis@ethernerd.net" },
]
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = [
    "prometheus-client>=0.21.1",
    "libtado>=4,<5",
]
